/use_sim_time: true
/simulation_mode: true
/useTruePos: false
/scaleRadius: true
/numRobots: 7
/maxNeighbors: 10
/neighborDist: 15.0
/timeHorizon: 10.0
/timeHorizonObst: 10.0
/thresholdGoal: 0.1
/thresholdLastSeen: 1.0
/nrIntialGuess: 20.0
/noiseStd: 0.0
robot_0:
    wheel_base: 0.4
    maxSpeed_linear: 0.5
    maxSpeed_angular: 1.0
    minSpeed_linear: 0.01
    minSpeed_angular: 0.01
    radius: 0.36
    goal:
        x: -3.402082
        y: 3.202082
        ang: 45.000000
robot_1:
    wheel_base: 0.4
    maxSpeed_linear: 0.5
    maxSpeed_angular: 1.0
    minSpeed_linear: 0.01
    minSpeed_angular: 0.01
    radius: 0.36
    goal:
        x: -3.889311
        y: 1.809660
        ang: 96.428571
robot_2:
    wheel_base: 0.4
    maxSpeed_linear: 0.5
    maxSpeed_angular: 1.0
    minSpeed_linear: 0.01
    minSpeed_angular: 0.01
    radius: 0.36
    goal:
        x: -3.104455
        y: 0.560569
        ang: 147.857143
robot_3:
    wheel_base: 0.4
    maxSpeed_linear: 0.5
    maxSpeed_angular: 1.0
    minSpeed_linear: 0.01
    minSpeed_angular: 0.01
    radius: 0.36
    goal:
        x: -1.638526
        y: 0.395398
        ang: 199.285714
robot_4:
    wheel_base: 0.4
    maxSpeed_linear: 0.5
    maxSpeed_angular: 1.0
    minSpeed_linear: 0.01
    minSpeed_angular: 0.01
    radius: 0.36
    goal:
        x: -0.595398
        y: 1.438526
        ang: 250.714286
robot_5:
    wheel_base: 0.4
    maxSpeed_linear: 0.5
    maxSpeed_angular: 1.0
    minSpeed_linear: 0.01
    minSpeed_angular: 0.01
    radius: 0.36
    goal:
        x: -0.760569
        y: 2.904455
        ang: 302.142857
robot_6:
    wheel_base: 0.4
    maxSpeed_linear: 0.5
    maxSpeed_angular: 1.0
    minSpeed_linear: 0.01
    minSpeed_angular: 0.01
    radius: 0.36
    goal:
        x: -2.009660
        y: 3.689311
        ang: 353.571429
