/use_sim_time: true
/simulation_mode: true
/useTruePos: false
/scaleRadius: false
/numRobots: 4
/maxNeighbors: 10
/neighborDist: 15.0
/timeHorizon: 10.0
/timeHorizonObst: 10.0
/thresholdGoal: 0.1
/thresholdLastSeen: 1.0
/nrIntialGuess: 20.0
/noiseStd: 0.0
robot_0:
    wheel_base: 0.4
    maxSpeed_linear: 0.5
    maxSpeed_angular: 1.0
    minSpeed_linear: 0.01
    minSpeed_angular: 0.01
    radius: 0.36
    goal:
        x: -3.614214
        y: 3.414214
        ang: 45.000000
robot_1:
    wheel_base: 0.4
    maxSpeed_linear: 0.5
    maxSpeed_angular: 1.0
    minSpeed_linear: 0.01
    minSpeed_angular: 0.01
    radius: 0.36
    goal:
        x: -3.614214
        y: 0.585786
        ang: 135.000000
robot_2:
    wheel_base: 0.4
    maxSpeed_linear: 0.5
    maxSpeed_angular: 1.0
    minSpeed_linear: 0.01
    minSpeed_angular: 0.01
    radius: 0.36
    goal:
        x: -0.785786
        y: 0.585786
        ang: 225.000000
robot_3:
    wheel_base: 0.4
    maxSpeed_linear: 0.5
    maxSpeed_angular: 1.0
    minSpeed_linear: 0.01
    minSpeed_angular: 0.01
    radius: 0.36
    goal:
        x: -0.785786
        y: 3.414214
        ang: 315.000000
